services:
  joystream-node:
    image: joystream/node:latest
    restart: unless-stopped
    container_name: joystream-node
    volumes:
      - chain-data:/data
    command:
      '--chain dev --alice --validator --pruning=archive --unsafe-ws-external --unsafe-rpc-external
      --rpc-methods Safe --rpc-cors=all --log runtime --base-path /data --no-hardware-benchmarks'
    ports:
      - 127.0.0.1:${JOYSTREAM_NODE_HTTP_PORT}:${JOYSTREAM_NODE_HTTP_PORT}
      - 127.0.0.1:${JOYSTREAM_NODE_WS_PORT}:${JOYSTREAM_NODE_WS_PORT}

volumes:
  chain-data:
    driver: local
